
export const CONTACTS_DATA = [
  { nombre: 'Actividades Academicas', email: 'aa@cine.unt.edu.ar' },
  { nombre: 'Adrian Di Toro', email: 'aditoro@cine.unt.edu.ar' },
  { nombre: 'Aldo Ternavasio', email: 'a.ternavasio@cine.unt.edu.ar' },
  { nombre: 'Alejandra Guzzo', email: 'a.guzzo@cine.unt.edu.ar' },
  { nombre: 'Alejandro Saya', email: 'a.saya@cine.unt.edu.ar' },
  { nombre: 'Amadeo Pellegrino', email: 'a.pellegrino@cine.unt.edu.ar' },
  { nombre: 'Ana Claudia Garcia', email: 'a.garcia@cine.unt.edu.ar' },
  { nombre: 'Angie Garcia del Moral', email: 'agarciadelmoral@cine.unt.edu.ar' },
  { nombre: 'Ariel Omar Bautista Tarqui', email: 'abautistatarqui@cine.unt.edu.ar' },
  { nombre: 'Arturo Horacio Carrasco', email: 'a.carrasco@cine.unt.edu.ar' },
  { nombre: 'Barbara Tarcic', email: 'b.tarcic@cine.unt.edu.ar' },
  { nombre: 'Benjamin Avila', email: 'b.avila@cine.unt.edu.ar' },
  { nombre: 'Bernabé Quiroga', email: 'b.quiroga@cine.unt.edu.ar' },
  { nombre: 'Bernardo Vides Almonacid', email: 'b.videsalmonacid@cine.unt.edu.ar' },
  { nombre: 'Blas Rivadeneira', email: 'b.rivadeneira@cine.unt.edu.ar' },
  { nombre: 'Candelaria Gimenez Lascano', email: 'cgimenezlascano@cine.unt.edu.ar' },
  { nombre: 'Carolina Coppens', email: 'c.coppens@cine.unt.edu.ar' },
  { nombre: 'Carolina María Lobo Paz', email: 'clobo@cine.unt.edu.ar' },
  { nombre: 'Centro Estudiantes Escuela de Cine', email: 'centro.estudiantes@cine.unt.edu.ar' },
  { nombre: 'Claudio Cecchin', email: 'cecchin@cine.unt.edu.ar' },
  { nombre: 'Compras y Bienes Escuela de Cine - UNT', email: 'compras@cine.unt.edu.ar' },
  { nombre: 'Comunicaciones EUCVyTV - UNT', email: 'comunicaciones@cine.unt.edu.ar' },
  { nombre: 'Contabilidad y Finanzas Escuela de Cine', email: 'contable@cine.unt.edu.ar' },
  { nombre: 'Daniel Agustín Araujo', email: 'd.araujo@cine.unt.edu.ar' },
  { nombre: 'DDHH y Género Escuela de Cine', email: 'genero@cine.unt.edu.ar' },
  { nombre: 'Defensa de Tésis Escuela de Cine', email: 'defensatesis@cine.unt.edu.ar' },
  { nombre: 'Departamento Alumnos Esc. Cine - UNT', email: 'alumnos@cine.unt.edu.ar' },
  { nombre: 'Departamento Biblioteca Esc. de Cine - UNT', email: 'biblioteca@cine.unt.edu.ar' },
  { nombre: 'Departamento Concursos', email: 'concursos@cine.unt.edu.ar' },
  { nombre: 'Departamento de Documentación y Archivo Cine UNT', email: 'dda@cine.unt.edu.ar' },
  { nombre: 'Departamento Informatica', email: 'informatica@cine.unt.edu.ar' },
  { nombre: 'Despacho de la Escuela de Cine', email: 'despacho@cine.unt.edu.ar' },
  { nombre: 'Diego Viruel', email: 'd.viruel@cine.unt.edu.ar' },
  { nombre: 'digitalizacion Archivo Documental', email: 'digitalizacion@cine.unt.edu.ar' },
  { nombre: 'Dirección Académica', email: 'd.academica@cine.unt.edu.ar' },
  { nombre: 'Dirección Académica Escuela de Cine - UNT', email: 'sidcer@cine.unt.edu.ar' },
  { nombre: 'Dirección Administrativa', email: 'administracion@cine.unt.edu.ar' },
  { nombre: 'Dirección de la Escuela de Cine y Televisión UNT', email: 'direccion@cine.unt.edu.ar' },
  { nombre: 'Elena Burgo De Chazal', email: 'e.burgodechazal@cine.unt.edu.ar' },
  { nombre: 'Elizabeth Maidan', email: 'emaidan@cine.unt.edu.ar' },
  { nombre: 'Encargado de turno tarde', email: 'turno-tarde@cine.unt.edu.ar' },
  { nombre: 'Enrique Escaño', email: 'e.escano@cine.unt.edu.ar' },
  { nombre: 'Equipamiento CIPA', email: 'equipamiento@cine.unt.edu.ar' },
  { nombre: 'Escuela Universitaria de Cine UNT', email: 'escuela@cine.unt.edu.ar' },
  { nombre: 'Exequiel Jimenez', email: 'e.jimenez@cine.unt.edu.ar' },
  { nombre: 'expedientes Mesa de Entradas', email: 'expedientes@cine.unt.edu.ar' },
  { nombre: 'Extension Cine', email: 'extension@cine.unt.edu.ar' },
  { nombre: 'Fabian Soberon', email: 'f.soberon@cine.unt.edu.ar' },
  { nombre: 'Federico Santilli', email: 'f.santilli@cine.unt.edu.ar' },
  { nombre: 'Felipe Cerisola', email: 'f.cerisola@cine.unt.edu.ar' },
  { nombre: 'Florencia Padilla', email: 'f.padilla@cine.unt.edu.ar' },
  { nombre: 'Francisco Pedemonte', email: 'f.pedemonte@cine.unt.edu.ar' },
  { nombre: 'Gallucci Escuela de cine', email: 'f.gallucci@cine.unt.edu.ar' },
  { nombre: 'Germán Azcoaga', email: 'g.azcoaga@cine.unt.edu.ar' },
  { nombre: 'Guillermo Del Pino', email: 'g.delpino@cine.unt.edu.ar' },
  { nombre: 'Gustavo Caro', email: 'g.caro@cine.unt.edu.ar' },
  { nombre: 'Higiene y Seguridad Cine', email: 'hys@cine.unt.edu.ar' },
  { nombre: 'Inés Silva', email: 'isilva@cine.unt.edu.ar' },
  { nombre: 'Informes Escuela', email: 'informes@cine.unt.edu.ar' },
  { nombre: 'Ingreso Escuela de Cine', email: 'ingreso@cine.unt.edu.ar' },
  { nombre: 'Jorge Luis Grimaldi', email: 'j.grimaldi@cine.unt.edu.ar' },
  { nombre: 'Jornadas Estética Cine y Política Escuela de Cine - UNT', email: 'jornadasecp@cine.unt.edu.ar' },
  { nombre: 'José Fernando Diaz', email: 'jdiaz@cine.unt.edu.ar' },
  { nombre: 'Jose Guzzi', email: 'j.guzzi@cine.unt.edu.ar' },
  { nombre: 'José Villafañe', email: 'j.villa@cine.unt.edu.ar' },
  { nombre: 'Josefina Caceres', email: 'jcaceres@cine.unt.edu.ar' },
  { nombre: 'Juan Carlos Veiga', email: 'jveiga@cine.unt.edu.ar' },
  { nombre: 'Juan Mascaro', email: 'j.mascaro@cine.unt.edu.ar' },
  { nombre: 'Julio Cesar Molina Juarez', email: 'jmolina@cine.unt.edu.ar' },
  { nombre: 'Laura DeArriba', email: 'l.dearriba@cine.unt.edu.ar' },
  { nombre: 'Leandro Suarez', email: 'lsuarez@cine.unt.edu.ar' },
  { nombre: 'Lucas Garcia Melo', email: 'l.garciamelo@cine.unt.edu.ar' },
  { nombre: 'Magdalena Franco', email: 'mfranco@cine.unt.edu.ar' },
  { nombre: 'Magdalena Osimani', email: 'mosimani@cine.unt.edu.ar' },
  { nombre: 'mantenimiento general', email: 'mantenimiento@cine.unt.edu.ar' },
  { nombre: 'Mantenimiento Técnico', email: 'tecnico@cine.unt.edu.ar' },
  { nombre: 'Manuel Canseco', email: 'm.canseco@cine.unt.edu.ar' },
  { nombre: 'Marcelo Piazza', email: 'm.piazza@cine.unt.edu.ar' },
  { nombre: 'María José Lavergne', email: 'mlavergne@cine.unt.edu.ar' },
  { nombre: 'Maria Jose Medina', email: 'mjmedina@cine.unt.edu.ar' },
  { nombre: 'María Lenis', email: 'm.lenis@cine.unt.edu.ar' },
  { nombre: 'María Sofía Hortt', email: 'mshortt@cine.unt.edu.ar' },
  { nombre: 'Mariana Araoz', email: 'm.araoz@cine.unt.edu.ar' },
  { nombre: 'Maximiliano Etchandy', email: 'metchandy@cine.unt.edu.ar' },
  { nombre: 'Melina Dulci', email: 'm.dulci@cine.unt.edu.ar' },
  { nombre: 'Mesa de Entradas Esc. de Cine Video y Tv', email: 'mesa@cine.unt.edu.ar' },
  { nombre: 'Nicolas Araoz', email: 'n.araoz@cine.unt.edu.ar' },
  { nombre: 'Nicolas Sarmiento', email: 'n.sarmiento@cine.unt.edu.ar' },
  { nombre: 'Oficina de Informes', email: 'informacion@cine.unt.edu.ar' },
  { nombre: 'Pedro Arturo Gomez', email: 'p.gomez@cine.unt.edu.ar' },
  { nombre: 'Pedro Eugenio Guaraz', email: 'pguaraz@cine.unt.edu.ar' },
  { nombre: 'Pedro Ponce', email: 'p.ponce@cine.unt.edu.ar' },
  { nombre: 'Proyector Led', email: 'proyectores@cine.unt.edu.ar' },
  { nombre: 'Reserva Aulas', email: 'reservas-aulas@cine.unt.edu.ar' },
  { nombre: 'Romina Leguizamon', email: 'r.leguizamon@cine.unt.edu.ar' },
  { nombre: 'Romina Nahas', email: 'r.nahas@cine.unt.edu.ar' },
  { nombre: 'Romina Romano', email: 'r.romano@cine.unt.edu.ar' },
  { nombre: 'Ruben Brasero', email: 'r.brasero@cine.unt.edu.ar' },
  { nombre: 'Secretaría - Sec. Académica', email: 's.academica@cine.unt.edu.ar' },
  { nombre: 'Secretaria de Dirección Académica Escuela de Cine - UNT', email: 'sec.d.academica@cine.unt.edu.ar' },
  { nombre: 'secretaria Dirección de Escuela', email: 'sde@cine.unt.edu.ar' },
  { nombre: 'Sector Personal', email: 'personal@cine.unt.edu.ar' },
  { nombre: 'Seguimiento de expedientes Académicos', email: 'segui-acd@cine.unt.edu.ar' },
  { nombre: 'Seguimiento de Expedientes Administración', email: 'segui-adm@cine.unt.edu.ar' },
  { nombre: 'Sergio Olivera', email: 's.olivera@cine.unt.edu.ar' },
  { nombre: 'SIlvia Patricia Portillo', email: 'sportillo@cine.unt.edu.ar' },
  { nombre: 'Tesorería Escuela de Cine - UNT', email: 'tesoreria@cine.unt.edu.ar' },
  { nombre: 'Títulos Escuela de Cine', email: 'titulos@cine.unt.edu.ar' },
  { nombre: 'Trabajo de Tesis Escuela de Cine', email: 'tesis@cine.unt.edu.ar' },
  { nombre: 'Viajes Docentes', email: 'viajes@cine.unt.edu.ar' },
  { nombre: 'Victor Martinez', email: 'v.martinez@cine.unt.edu.ar' },
];
